"""
correction_loop.py
------------------
LangChain-backed SQL correction loop.

This module repairs invalid SQL generated by the LLM.
It is used when validation fails or PostgreSQL execution raises an error.
"""

import re

from practice.sql_validator import validate_sql as validate_read_only_sql


def clean_sql_response(response_text):
    if not response_text:
        raise ValueError("LLM returned empty correction response")

    sql = response_text.strip()
    sql = re.sub(r"```sql", "", sql, flags=re.IGNORECASE)
    sql = sql.replace("```", "").strip()

    match = re.search(
        r"\b(WITH|SELECT)\b[\s\S]*?;",
        sql,
        flags=re.IGNORECASE
    )

    if match:
        cleaned_sql = match.group(0).strip()
    else:
        lines = sql.splitlines()
        collecting = False
        parts = []

        for line in lines:
            clean_line = line.strip()
            upper_line = clean_line.upper()

            if upper_line.startswith("SELECT") or upper_line.startswith("WITH"):
                collecting = True

            if collecting:
                parts.append(clean_line)

        cleaned_sql = " ".join(parts) if parts else sql

    cleaned_sql = re.sub(r"\s+", " ", cleaned_sql).strip()

    if cleaned_sql and not cleaned_sql.endswith(";"):
        cleaned_sql += ";"

    return cleaned_sql


def validate_corrected_sql(sql):
    is_valid, message = validate_read_only_sql(sql)

    if not is_valid:
        raise ValueError(message)

    return True


def fix_sql(generator, question, wrong_sql, error_message):
    """
    Fix SQL using LangChain.

    If SQLGenerator has fix_sql_with_langchain(), we use it.
    Otherwise, we fall back to call_gemini_raw() for backward compatibility.
    """
    try:
        if hasattr(generator, "fix_sql_with_langchain"):
            corrected_sql = generator.fix_sql_with_langchain(
                question=question,
                wrong_sql=wrong_sql,
                error_message=error_message
            )
        else:
            correction_prompt = f"""
You are an expert PostgreSQL SQL correction assistant.

User question:
{question}

Wrong SQL:
{wrong_sql}

Error message:
{error_message}

Database schema:
- customers(customer_id, country, signup_date)
- products(product_id, product_name, category)
- orders(order_id, customer_id, order_date, status)
- order_items(order_id, product_id, quantity, price)

Rules:
- Return only corrected SQL.
- Use PostgreSQL syntax.
- Use only SELECT or WITH SELECT queries.
- Do not explain anything and do not include SQL comments.
- Do not use INSERT, UPDATE, DELETE, DROP, ALTER, TRUNCATE, CREATE, REPLACE, MERGE, GRANT, or REVOKE.
- End the SQL with one semicolon.
"""
            corrected_sql = generator.call_gemini_raw(correction_prompt)
            corrected_sql = clean_sql_response(corrected_sql)

        validate_corrected_sql(corrected_sql)
        return corrected_sql

    except Exception as exc:
        raise Exception(f"SQL correction failed: {exc}")
